// Localization utility
const translations = {
  en: {
    MY_TICKETS: "MY TICKETS",
    SCRATCH_TICKETS_REWARDS: "SCRATCH TICKETS AND UNLOCK REWARDS",
    SCRATCH_TICKETS: "SCRATCH TICKETS",
    BANK_STEPS: "BANK STEPS",
    ALPHA: "ALPHA",
    CHECK_OUT: "CHECK OUT",
    LEVEL_ABBR: "LV",
    SCRATCH_TICKET: "SCRATCH TICKET",
    SCRATCH_REWARDS: "SCRATCH YOUR TICKETS TO REVEAL REWARDS!",
    BANK_TICKET: "BANK TICKET",
    LUCKY_DRAW: "SAVE YOUR TICKETS TO ENTER A LUCKY DRAW",
    COMING_SOON: "COMING SOON",
    BURN_TICKET: "BURN TICKET",
    GOLDEN_TICKET: "BURN 1 TICKET DAILY FOR 7 CONSECUTIVE DAYS AND STAND A CHANCE TO RECEIVE A GOLDEN TICKET",
    EARN_EXTRA_TICKETS: "EARN EXTRA TICKETS BY INVITING FRIENDS OR BY COMPLETING DAILY TASKS. THE MORE YOU ENGAGE, THE MORE REWARDS YOU'LL UNLOCK.",
    LEVEL_UP_SLOTS: "UNLOCK 3 MORE SLOTS BY LEVELING UP TO LEVEL 2!",
    SCRATCH_1_TICKET: "SCRATCH 1 TICKET",
    SCRATCH_ALL_TICKETS: "SCRATCH ALL TICKETS",
    STARLETS: "STARLETS",
    TURN_STEPS_REWARDS: "TURN YOUR STEPS INTO INSTANT REWARDS!",
    NFT_SNEAKER_EARN: "EQUIP AND USE YOUR FIRST NFT SNEAKER, EARN GST AND GMT DAILY.",
    CLAIM_STARLETS: "CLAIM STARLETS",
    TIME_LIMITED_TASKS: "TIME-LIMITED TASKS",
    FSL_ACADEMY: "FSL ACADEMY",
    PARTNER_TASKS: "PARTNER TASKS",
    FRIENDS: "FRIENDS",
    EARNED: "EARNED",
    TROPHIES: "TROPHIES",
    INVITE_FRIENDS: "INVITE FRIENDS",
    ROOKIE_RECRUITER: "ROOKIE RECRUITER",
    JUNIOR_AMBASSADOR: "JUNIOR AMBASSADOR",
    SENIOR_AMBASSADOR: "SENIOR AMBASSADOR",
    MASTER_CONNECTOR: "MASTER CONNECTOR",
    ELITE_INFLUENCER: "ELITE INFLUENCER",
    LEGENDARY_LUMINARY: "LEGENDARY LUMINARY",
    STARLETS_CHAMPION: "STARLETS CHAMPION",
    ALPHA_TESTER: "ALPHA TESTER",
    STEPS_OF_GLORY: "STEPS OF GLORY",
    LEVEL_1_4_INVITES: "1 - 4 INVITES",
    STARTING_OUT: "YOU'RE JUST STARTING OUT. KEEP SHARING TO CLIMB THE RANKS!",
    LEVEL_5_9_INVITES: "5 - 9 INVITES",
    GREAT_JOB: "GREAT JOB! YOU'RE BECOMING AN INFLUENTIAL MEMBER OF THE COMMUNITY.",
    LEVEL_10_19_INVITES: "10 - 19 INVITES",
    IMPRESSIVE: "IMPRESSIVE! YOUR EFFORTS ARE MAKING A SIGNIFICANT IMPACT.",
    LEVEL_20_49_INVITES: "20 - 49 INVITES",
    OUTSTANDING_WORK: "OUTSTANDING WORK! YOU'RE A KEY PLAYER IN GROWING OUR COMMUNITY.",
    LEVEL_50_99_INVITES: "50 - 99 INVITES",
    EXCEPTIONAL: "EXCEPTIONAL! YOU'RE AMONG THE TOP CONTRIBUTORS.",
    LEGENDARY_STATUS: "LEGENDARY STATUS ACHIEVED! YOU'RE A CORNERSTONE OF OUR GROWTH.",
    BECAME_STARLET: "YOU DIDN'T JUST COLLECT STARLETS YOU BECAME ONE!",
    JOURNEY_PROOF: "PROOF THAT YOU WERE THERE WHEN THE JOURNEY BEGAN.",
    GLOBAL_RUN: "ONE DAY. ONE MISSION. ONE GLOBAL RUN. AWARDED TO RUNNERS WHO MOVED WITH THE WORLD ON JUNE 4TH.",
    TICKETS: "TICKETS",
    STARLETS_UI: "STARLETS",
    MOOAR_MEMBERSHIP: "MOOAR+ MEMBERSHIP",
    ALPHA_CHEST: "ALPHA CHEST",
    NEED_STARLETS: "YOU NEED XX STARLETS TO REACH THE NEXT LEVEL.",
    LEVEL_UP: "LEVEL UP",
    EARN_STARLETS: "EARN STARLETS BY:",
    DAILY_CHECKIN_STREAK: "DAILY CHECK-IN: KEEP YOUR STREAK!",
    TICKETS_LUCK: "TICKETS: TRY YOUR LUCK AND WIN MORE POINTS.",
    TASKS_ENGAGE: "TASKS: ENGAGE WITH TASKS TO UNLOCK REWARDS.",
    SELECT_AVATAR: "SELECT AVATAR",
    OKAY: "OKAY",
    CONGRATULATIONS: "CONGRATULATIONS",
    WON_STARLETS: "YOU'VE WON 20 STARLETS!",
    CLAIM: "CLAIM",
    CONGRATULATIONS_UI: "CONGRATULATIONS!",
    LEVEL_2_LEGEND: "ONLY LEGENDS REACH LEVEL 2!",
    OKAY_UI: "OKAY",
    CHECK_IN: "CHECK-IN",
    TODAY: "TODAY",
    EARN_EGGLETS: "EARN EGGLETS",
    EGGLET_EVENT: "EGGLET EVENT",
    LANGUAGE: "LANGUAGE",
    LOGIN_ERROR: "Unable to log in. Please try again.",
    RETRY: "Retry",
    LOG_IN_STREAK: "LOG IN STREAK",
    DAY: "DAY",
    DAYS: "DAYS"
  },
  ja: {
    MY_TICKETS: "マイチケット",
    SCRATCH_TICKETS_REWARDS: "スクラッチで報酬を獲得",
    SCRATCH_TICKETS: "スクラッチ",
    BANK_STEPS: "ステップバンク",
    ALPHA: "アルファ",
    CHECK_OUT: "確認する",
    LEVEL_ABBR: "LV",
    SCRATCH_TICKET: "スクラッチチケット",
    SCRATCH_REWARDS: "チケットを削って報酬をゲットしよう！",
    BANK_TICKET: "チケットバンク",
    LUCKY_DRAW: "チケットを貯めて抽選に参加しよう",
    COMING_SOON: "近日公開",
    BURN_TICKET: "チケットを燃やす",
    GOLDEN_TICKET: "7日間連続で毎日1枚チケットを燃やすと、ゴールデンチケットを獲得できるチャンス！",
    EARN_EXTRA_TICKETS: "友達を招待したりデイリータスクを達成したりして、追加チケットを獲得しよう。参加すればするほど報酬が増えるよ！",
    LEVEL_UP_SLOTS: "レベル2にアップするとスロットが3つ解放！",
    SCRATCH_1_TICKET: "チケットを1枚削る",
    SCRATCH_ALL_TICKETS: "すべてのチケットを削る",
    STARLETS: "スターレット",
    TURN_STEPS_REWARDS: "歩数をすぐに報酬に変えよう！",
    NFT_SNEAKER_EARN: "初めてのNFTスニーカーを装備して使おう。毎日GSTとGMTを獲得できるよ。",
    CLAIM_STARLETS: "スターレットを受け取る",
    TIME_LIMITED_TASKS: "期間限定タスク",
    FSL_ACADEMY: "FSLアカデミー",
    PARTNER_TASKS: "パートナータスク",
    FRIENDS: "フレンド",
    EARNED: "獲得済み",
    TROPHIES: "トロフィー",
    INVITE_FRIENDS: "フレンドを招待",
    ROOKIE_RECRUITER: "ルーキーリクルーター",
    JUNIOR_AMBASSADOR: "ジュニアアンバサダー",
    SENIOR_AMBASSADOR: "シニアアンバサダー",
    MASTER_CONNECTOR: "マスターコネクター",
    ELITE_INFLUENCER: "エリートインフルエンサー",
    LEGENDARY_LUMINARY: "レジェンダリー・ルミナリー",
    STARLETS_CHAMPION: "スターレットチャンピオン",
    ALPHA_TESTER: "アルファテスター",
    STEPS_OF_GLORY: "栄光の歩み",
    LEVEL_1_4_INVITES: "1～4人招待",
    STARTING_OUT: "まだ始めたばかりだよ。もっとシェアしてランクアップしよう！",
    LEVEL_5_9_INVITES: "5～9人招待",
    GREAT_JOB: "すごい！コミュニティで影響力を持つメンバーになってきたよ。",
    LEVEL_10_19_INVITES: "10～19人招待",
    IMPRESSIVE: "素晴らしい！あなたの活動が大きな影響を与えているよ。",
    LEVEL_20_49_INVITES: "20～49人招待",
    OUTSTANDING_WORK: "素晴らしい活躍！コミュニティ成長の中心的存在だよ。",
    LEVEL_50_99_INVITES: "50～99人招待",
    EXCEPTIONAL: "卓越した活躍！トップ貢献者の一人だよ。",
    LEGENDARY_STATUS: "レジェンダリーステータス達成！あなたは私たちの成長を支える存在だよ。",
    BECAME_STARLET: "スターリットを集めただけじゃない、あなた自身がスターリットになったんだ！",
    JOURNEY_PROOF: "この旅の始まりにあなたがいた証。",
    GLOBAL_RUN: "1日。1つの使命。1つのグローバルラン。6月4日に世界と共に走ったランナーへ贈られる。",
    TICKETS: "チケット",
    STARLETS_UI: "スターレット",
    MOOAR_MEMBERSHIP: "MOOAR+メンバーシップ",
    ALPHA_CHEST: "アルファチェスト",
    NEED_STARLETS: "次のレベルに進むには<STARLET>スターレットが必要です。",
    LEVEL_UP: "レベルアップ",
    EARN_STARLETS: "スターレットの獲得方法:",
    DAILY_CHECKIN_STREAK: "デイリーチェックイン：連続記録を続けよう！",
    TICKETS_LUCK: "チケット：運試しでポイントをゲット！",
    TASKS_ENGAGE: "タスク：タスクをこなして報酬を獲得しよう。",
    SELECT_AVATAR: "アバターを選択",
    OKAY: "OK",
    CONGRATULATIONS: "おめでとう！",
    WON_STARLETS: "20スターレットを獲得したよ！",
    CLAIM: "受け取る",
    CONGRATULATIONS_UI: "おめでとう！",
    LEVEL_2_LEGEND: "レベル2に到達できるのはレジェンドだけ！",
    OKAY_UI: "OK",
    CHECK_IN: "チェックイン",
    TODAY: "今日",
    EARN_EGGLETS: "エグレットを獲得",
    EGGLET_EVENT: "エグレットイベント",
    LANGUAGE: "言語",
    LOGIN_ERROR: "ログインできませんでした。もう一度お試しください。",
    RETRY: "再試行",
    LOG_IN_STREAK: "ログインストリーク",
    DAY: "日",
    DAYS: "日"
  }
};

// Get current language from localStorage or default to English
const getCurrentLanguage = () => {
  return localStorage.getItem('language') || 'en';
};

// Set language
const setLanguage = (language) => {
  localStorage.setItem('language', language);
  window.location.reload(); // Simple reload to apply changes
};

// Get translation for a key
const t = (key) => {
  const currentLang = getCurrentLanguage();
  return translations[currentLang][key] || translations.en[key] || key;
};

// Export functions
export { t, getCurrentLanguage, setLanguage }; 